---
title: "CCFRP Central California Fork Length and Total Length Comparison"
author: "Rachel Brooks"
date: "2023-03-17"
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE, error=FALSE)

rm(list = ls());graphics.off()
library(tidyverse) # For data manipulation and summarization
library(plotrix) #To use standard error calculation
library(cowplot) #For grouping plots
library(scales) #For editing axis scales
library(rstatix) #For running ANCOVA
#library(ggpmisc) #adding equation and r2 to figures
library(here) ## for erin

alpha=0.5
formula<-y~x
theme_set(theme_classic(base_size=16))

```

Load Data

```{r}

length.data <-read.csv(here("Data", 'Fork-And-Total-Length-Data.csv'))

```
Blue/Deacon Rockfish

```{r blue deacon rf}

blue.deacon<-length.data%>%
  group_by(Institution, Species, Data.Source)%>%
  filter(Species == "Blue/Deacon Rockfish")

ggplot(blue.deacon, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Institution))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Blue/Deacon Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(blue.deacon, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Data.Source))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Blue/Deacon Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(blue.deacon, aes(x=Fork.Length..cm., y=Total.Length..cm.))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Blue/Deacon Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")
  
MOD <- lm(Fork.Length..cm.~Total.Length..cm., data = blue.deacon)
  summary(MOD)
  hist(MOD$residuals)

```

Black Rockfish

```{r black rf}

black<-length.data%>%
  group_by(Institution, Species, Data.Source)%>%
  filter(Species == "Black Rockfish")

ggplot(black, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Institution))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Black Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(black, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Data.Source))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Black Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(black, aes(x=Fork.Length..cm., y=Total.Length..cm.))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Black Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")
  
MOD <- lm(Fork.Length..cm.~Total.Length..cm., data = black)
  summary(MOD)
  hist(MOD$residuals)
  
```


Vermilion Rockfish

```{r vermilion rf}

vermilion<-length.data%>%
  group_by(Institution, Species, Data.Source)%>%
  filter(Species == "Vermilion Rockfish")

ggplot(vermilion, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Institution))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Vermilion Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(vermilion, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Data.Source))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Vermilion Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(vermilion, aes(x=Fork.Length..cm., y=Total.Length..cm.))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Vermilion Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")
  
MOD <- lm(Fork.Length..cm.~Total.Length..cm., data = vermilion)
  summary(MOD)
  hist(MOD$residuals)
  
```



Olive/Yellowtail Rockfish

```{r olive yellowtail rf}

olive.yellowtail<-length.data%>%
  group_by(Institution, Species, Data.Source)%>%
  filter(Species == "Olive/Yellowtail Rockfish")

ggplot(olive.yellowtail, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Institution))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Olive/Yellowtail Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(olive.yellowtail, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Data.Source))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Olive/Yellowtail Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(olive.yellowtail, aes(x=Fork.Length..cm., y=Total.Length..cm.))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Olive/Yellowtail Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")
  
MOD <- lm(Fork.Length..cm.~Total.Length..cm., data = olive.yellowtail)
#MOD2 <- lm(Total.Length..cm.~Fork.Length..cm., data = olive.yellowtail)
  summary(MOD)
  #summary(MOD2)
  hist(MOD$residuals)
  
```

Copper Rockfish

```{r copper rf}

copper<-length.data%>%
  group_by(Institution, Species, Data.Source)%>%
  filter(Species == "Copper Rockfish")

ggplot(copper, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Institution))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Copper Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(copper, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Data.Source))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Copper Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(copper, aes(x=Fork.Length..cm., y=Total.Length..cm.))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Copper Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")
  
MOD <- lm(Fork.Length..cm.~Total.Length..cm., data = copper)
  summary(MOD)
  hist(MOD$residuals)
  
```


Canary Rockfish

```{r canary rf}

canary<-length.data%>%
  group_by(Institution, Species, Data.Source)%>%
  filter(Species == "Canary Rockfish")

ggplot(canary, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Institution))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Canary Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(canary, aes(x=Fork.Length..cm., y=Total.Length..cm., col=Data.Source))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Canary Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")

ggplot(canary, aes(x=Fork.Length..cm., y=Total.Length..cm.))+
  geom_point()+
  geom_smooth(method = "lm")+ 
  ggtitle("Canary Rockfish") +
  xlab("Fork Length (cm)") + ylab("Total Length (cm)")
  
MOD <- lm(Fork.Length..cm.~Total.Length..cm., data = canary)
  summary(MOD)
  hist(MOD$residuals)
  
```


Same comparisons, but binned in 2 cm length bins


```{r data part II}

length_dat <- read_csv(here("Data", "Fork-And-Total-Length-Data2.csv"))
str(length_dat)

length_dat %>% arrange(desc(TL)) %>% slice(1)
length_dat %>% arrange(desc(FL)) %>% slice(1)
length_dat %>% arrange(TL) %>% slice(1)
length_dat %>% arrange(FL) %>% slice(1)


```

```{r bin data categories}

bin_dat <- length_dat %>%
  mutate(TL_bin = cut(TL, breaks = c(0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,
                                     32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,
                                     62,64)),
         FL_bin = cut(FL, breaks = c(0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,
                                     32,34,36,38,40,42,44,46,48,50,52,54,56,58,60,
                                     62,64)),
         match = case_when(
           TL_bin == FL_bin ~ "YES",
           TL_bin != FL_bin ~ "NO"
         ))

## checking out some numbers
# bin_dat %>% count(match)
# bin_dat %>% filter(Species == "Blue/Deacon Rockfish") %>% count(match)
# bin_dat %>% filter(!Species == "Canary Rockfish") %>% count(match)
# 
# ggplot(data = bin_dat)+
#   geom_bar(aes(x = TL_bin), fill = "Blue", alpha = 0.5)+
#   geom_bar(aes(x = FL_bin), fill = "Green", alpha = 0.5)

```


```{r bin data integers}

## the annoying long bin conversion

bin_dat_num <- bin_dat %>%
  mutate(TL_int = case_when(
    TL %in% c(11,12) ~ 12,
    TL %in% c(13,14) ~ 14,
    TL %in% c(15,16) ~ 16,
    TL %in% c(17,18) ~ 18,
    TL %in% c(19,20) ~ 20,
    TL %in% c(21,22) ~ 22,
    TL %in% c(23,24) ~ 24,
    TL %in% c(25,26) ~ 26,
    TL %in% c(27,28) ~ 28,
    TL %in% c(29,30) ~ 30,
    TL %in% c(31,32) ~ 32,
    TL %in% c(33,34) ~ 34,
    TL %in% c(35,36) ~ 36,
    TL %in% c(37,38) ~ 38,
    TL %in% c(39,40) ~ 40,
    TL %in% c(41,42) ~ 42,
    TL %in% c(43,44) ~ 44,
    TL %in% c(45,46) ~ 46,
    TL %in% c(47,48) ~ 48,
    TL %in% c(49,50) ~ 50,
    TL %in% c(51,52) ~ 52,
    TL %in% c(53,54) ~ 54,
    TL %in% c(55,56) ~ 56,
    TL %in% c(57,58) ~ 58,
    TL %in% c(59,60) ~ 60,
    TL %in% c(61,62) ~ 62,
    TL %in% c(63,64) ~ 64),
    FL_int = case_when(
      FL %in% c(11,12) ~ 12,
      FL %in% c(13,14) ~ 14,
      FL %in% c(15,16) ~ 16,
      FL %in% c(17,18) ~ 18,
      FL %in% c(19,20) ~ 20,
      FL %in% c(21,22) ~ 22,
      FL %in% c(23,24) ~ 24,
      FL %in% c(25,26) ~ 26,
      FL %in% c(27,28) ~ 28,
      FL %in% c(29,30) ~ 30,
      FL %in% c(31,32) ~ 32,
      FL %in% c(33,34) ~ 34,
      FL %in% c(35,36) ~ 36,
      FL %in% c(37,38) ~ 38,
      FL %in% c(39,40) ~ 40,
      FL %in% c(41,42) ~ 42,
      FL %in% c(43,44) ~ 44,
      FL %in% c(45,46) ~ 46,
      FL %in% c(47,48) ~ 48,
      FL %in% c(49,50) ~ 50,
      FL %in% c(51,52) ~ 52,
      FL %in% c(53,54) ~ 54,
      FL %in% c(55,56) ~ 56,
      FL %in% c(57,58) ~ 58,
      FL %in% c(59,60) ~ 60,
      FL %in% c(61,62) ~ 62,
      FL %in% c(63,64) ~ 64),
    Diff_int = TL_int -FL_int)

```


```{r same analyses as RB}

## Blue/Deacon rockfish

BLU_DEA <- bin_dat_num %>%
  filter(Species == "Blue/Deacon Rockfish")

mod_BLU <- lm(TL_int ~ FL_int, data = BLU_DEA)
summary(mod_BLU)

## Black rockfish

BLA <- bin_dat_num %>%
  filter(Species == "Black Rockfish")

mod_BLA <- lm(TL_int ~ FL_int, data = BLA)
summary(mod_BLA)

## Vermilion rockfish

VER <- bin_dat_num %>%
  filter(Species == "Vermilion Rockfish")

mod_VER <- lm(TL_int ~ FL_int, data = VER)
summary(mod_VER)

## Olive/Yellowtail rockfish

OYT <- bin_dat_num %>%
  filter(Species == "Olive/Yellowtail Rockfish")

mod_OYT <- lm(TL ~ FL, data = OYT)
summary(mod_OYT)

## Copper rockfish

CPR <- bin_dat_num %>%
  filter(Species == "Copper Rockfish")

mod_CPR <- lm(TL_int ~ FL_int, data = CPR)
summary(mod_CPR)

## Canary rockfish

CNY <- bin_dat_num %>%
  filter(Species == "Canary Rockfish")

mod_CNY <- lm(TL_int ~ FL_int, data = CNY)
summary(mod_CNY)


```



```{r theoretical data}

dummy_dat <- data.frame(FL = seq(11,63, by = 1))

dummy_dat_bin <- dummy_dat %>%
  mutate(TL_blu = 1.00265*FL + 0.79841,
         TL_bla = 0.9573*FL + 2.1143,
         TL_ver = 1.02015*FL + 0.12161,
         TL_oyt = 0.99923*FL + 0.67290,
         TL_cpr = 1*FL + 0,
         TL_cny = 1.057358*FL - 0.17298)

dummy_dat_rb

```

